# Generated by Django 3.0 on 2020-10-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefecture',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
