# Generated by Django 3.0 on 2021-10-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefectures', '0004_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='name_jp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
