# Generated by Django 3.0 on 2021-10-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefectures', '0005_countrycode_name_jp'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefecture',
            name='name_en',
            field=models.CharField(default='', max_length=255),
        ),
    ]
