# Generated by Django 3.0 on 2020-10-02 06:09

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prefectures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('reward_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('official_reward_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seller', models.BooleanField(default=False)),
                ('shop_name', models.CharField(default='', max_length=255)),
                ('tel', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=255)),
                ('user_code', models.CharField(max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('real_name', models.CharField(default='', max_length=255)),
                ('gender', models.SmallIntegerField(choices=[(0, 'NONE'), (1, 'MALE'), (2, 'FEMALE')], null=True)),
                ('birthday', models.DateField(null=True)),
                ('zipcode', models.CharField(default='', max_length=7)),
                ('city', models.CharField(default='', max_length=100)),
                ('address1', models.CharField(default='', max_length=255)),
                ('address2', models.CharField(default='', max_length=255)),
                ('corporate_name', models.CharField(default='', max_length=255)),
                ('message_notification', models.BooleanField(default=False)),
                ('other_notification', models.BooleanField(default=False)),
                ('allowed_by_id', models.BooleanField(default=False)),
                ('allowed_by_tel', models.BooleanField(default=False)),
                ('word', models.CharField(default='', max_length=255)),
                ('salon_category', models.SmallIntegerField(choices=[(1, 'SALONS'), (2, 'STYLISTS')], null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Authority')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
                ('introducer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prefectures.Prefecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('order_count', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('sales_amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('tax', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('amount_tax_included', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('shipping_fee', models.BigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('total_amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserCommision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('order_count', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('tax', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('total_amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('paid_date', models.DateField(null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'UNPAID'), (1, 'PAID')], null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('zip1', models.CharField(max_length=8)),
                ('address1', models.CharField(max_length=1024)),
                ('address2', models.CharField(default='', max_length=1024)),
                ('tel', models.CharField(max_length=32)),
                ('is_default', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prefectures.Prefecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
