# Generated by Django 3.0 on 2020-10-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authority',
            old_name='official_reward_rate',
            new_name='commission_rate',
        ),
        migrations.RenameField(
            model_name='authority',
            old_name='reward_rate',
            new_name='official_commission_rate',
        ),
        migrations.AddField(
            model_name='authority',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
