# Generated by Django 3.0 on 2020-10-07 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prefectures', '0002_auto_20201006_0515'),
        ('profiles', '0003_auto_20201006_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prefectures.Prefecture'),
        ),
    ]
