# Generated by Django 3.0 on 2020-10-08 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201007_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='address',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='authority',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='authority',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='monthlypayment',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='usercommision',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='usercommision',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='usersale',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='usersale',
            name='update_date',
        ),
        migrations.AddField(
            model_name='address',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authority',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authority',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercommision',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercommision',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersale',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersale',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
