# Generated by Django 3.0 on 2020-10-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201008_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='corporate_tel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='representative_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
