# Generated by Django 3.0 on 2020-10-09 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201008_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_name', models.CharField(max_length=100)),
                ('financial_code', models.CharField(max_length=4)),
                ('account_type', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('branch_code', models.CharField(max_length=3)),
                ('branch_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=7)),
                ('account_name', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
