# Generated by Django 3.0 on 2020-10-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_financialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payload',
            field=models.TextField(null=True),
        ),
    ]
