# Generated by Django 3.0 on 2020-10-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_payload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='message_notification',
            new_name='message_notification_mail',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='other_notification',
            new_name='message_notification_phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='memo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_notification_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_notification_phone',
            field=models.BooleanField(default=False),
        ),
    ]
