# Generated by Django 3.0 on 2020-10-24 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20201022_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='memo',
        ),
    ]
