# Generated by Django 3.0 on 2020-11-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
