# Generated by Django 3.0 on 2020-11-22 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20201008_0125'),
        ('profiles', '0011_profile_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_img', to='images.Image'),
        ),
    ]
