# Generated by Django 3.0 on 2020-12-05 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prefectures', '0004_countrycode'),
        ('profiles', '0013_auto_20201202_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tel_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prefectures.CountryCode'),
        ),
    ]
