# Generated by Django 3.0 on 2020-12-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prefectures', '0004_countrycode'),
        ('profiles', '0014_profile_tel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='tel_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prefectures.CountryCode'),
        ),
    ]
