# Generated by Django 3.0 on 2020-12-08 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prefectures', '0004_countrycode'),
        ('profiles', '0015_auto_20201206_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='corporate_tel_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_tel_code', to='prefectures.CountryCode'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_tel_code', to='prefectures.CountryCode'),
        ),
    ]
