# Generated by Django 3.0 on 2020-12-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_remove_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='tel_code',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='corporate_tel_code',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel_code',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
