# Generated by Django 3.0 on 2021-01-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20201213_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
