# Generated by Django 3.0 on 2021-02-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20210106_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
