# Generated by Django 3.0 on 2021-04-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20210209_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allowed_by_id',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allowed_by_tel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='message_notification_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_notification_mail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_notification_phone',
            field=models.BooleanField(default=True),
        ),
    ]
