# Generated by Django 3.0 on 2021-08-31 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20210415_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(blank=True, default='', max_length=128)),
                ('brand_name', models.CharField(blank=True, default='', max_length=128)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('os_version', models.CharField(blank=True, default='', max_length=128)),
                ('errors', models.CharField(blank=True, default='', max_length=1024)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
