# Generated by Django 3.0 on 2021-08-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_errorlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlogs',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
