# Generated by Django 3.0 on 2021-08-31 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_errorlogs_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlogs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
