# Generated by Django 3.0 on 2021-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20210831_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlogs',
            name='status',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
