version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/var/www/kinujo_production
hooks:
 BeforeInstall:
   - location: deploy/prod/before_install.sh
     timeout: 300
     runas: ec2-user
 AfterInstall:
   - location: deploy/prod/after_install.sh
     timeout: 300
     runas: ec2-user
