# Generated by Django 3.0 on 2020-10-08 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='update_date',
        ),
        migrations.AddField(
            model_name='policy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
