# Generated by Django 3.0 on 2020-10-06 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrate',
            name='month',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='year',
        ),
        migrations.AddField(
            model_name='taxrate',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
