"""
Django settings for kinujo project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from .shared_settings import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ro6hl1+%(r+oek3sz3j8x!dfyy+_3e+*so0q-zec9f-ycp5fox'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['kinujo-release.c2sg.asia', 'demo.cl91mjsmzfrn.ap-southeast-1.rds.amazonaws.com' ]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kinujo_release_db',
        'USER': 'kinujo_release',
        'PASSWORD': 'Pa55w0rd',
        'HOST': 'demo.cl91mjsmzfrn.ap-southeast-1.rds.amazonaws.com',
        'PORT': '3306',
    }
}

# s3 settings
AWS_ACCESS_KEY_ID = 'AKIAI3VAZN6IG4F7I7SQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'kinujo-release'
S3_URL = 'https://%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

DEFAULT_FILE_STORAGE = 'utilities.s3utils.MediaS3BotoStorageRelease'
MEDIA_DIRECTORY = '/release/media/'
MEDIA_URL = S3_URL + MEDIA_DIRECTORY
MEDIA_ROOT = MEDIA_URL
WEB_URL = MEDIA_URL

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_LOCAL = os.path.join(BASE_DIR, 'media')
