# Generated by Django 3.0 on 2020-10-02 06:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prefectures', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('zip1', models.CharField(max_length=8)),
                ('address1', models.CharField(max_length=1024)),
                ('address2', models.CharField(default='', max_length=1024)),
                ('tel', models.CharField(max_length=32)),
                ('pic_name', models.CharField(max_length=128)),
                ('pic_tel', models.CharField(max_length=32)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prefectures.Prefecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
