# Generated by Django 3.0 on 2020-10-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_financialaccount'),
        ('prefectures', '0003_auto_20201008_0125'),
        ('salons', '0002_auto_20201008_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salons',
            new_name='Salon',
        ),
    ]
