# Generated by Django 3.0 on 2020-10-02 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reduced_tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
