# Generated by Django 3.0 on 2020-10-02 06:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('prefectures', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('tax', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('shipping_fee', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('total_amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('name', models.CharField(max_length=128)),
                ('zip1', models.CharField(max_length=8)),
                ('address1', models.CharField(max_length=1024)),
                ('address2', models.CharField(default='', max_length=1024)),
                ('tel', models.CharField(max_length=32)),
                ('payment', models.CharField(max_length=255)),
                ('customer_remark', models.TextField(default='')),
                ('remark', models.TextField(default='')),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prefectures.Prefecture')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_purchaser', to='profiles.Profile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_seller', to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('unit_price', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('total_price', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('tax', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('total_amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product_jan_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductJancode')),
            ],
        ),
        migrations.CreateModel(
            name='TotalSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('sales_amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('tax', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('amount_tax_included', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('shipping_fee', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('total_amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('order_count', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('order_count', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Authority')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_copy', models.BooleanField(default=False)),
                ('to_name', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('output_date', models.DateField(default=datetime.date.today)),
                ('order_date', models.DateField(default=datetime.datetime.now)),
                ('product_name', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('payment', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('is_sales', models.BooleanField(default=False)),
                ('is_food', models.BooleanField(default=False)),
                ('shipping_fee', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
