# Generated by Django 3.0 on 2020-10-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201008_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='amount',
            new_name='quantity',
        ),
    ]
