# Generated by Django 3.0 on 2020-10-28 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201009_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inquiry_number',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'IN PROCESSING'), (2, 'SHIPMENT COMPLETE')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
