# Generated by Django 3.0 on 2020-12-02 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201028_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'NEW'), (1, 'IN PROCESSING'), (2, 'SHIPMENT COMPLETE')], null=True),
        ),
        migrations.AlterField(
            model_name='orderreceipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderReceipts', to='orders.Order'),
        ),
    ]
