# Generated by Django 3.0 on 2020-12-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_tel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'IN PROCESSING'), (2, 'SHIPMENT COMPLETE')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tel_code',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
