# Generated by Django 3.0 on 2021-02-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201213_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(null=True),
        ),
    ]
