# Generated by Django 3.0 on 2021-02-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210209_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
