# Generated by Django 3.0 on 2021-02-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210214_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
