# Generated by Django 3.0 on 2021-04-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210214_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
