LoadModule wsgi_module  /var/www/.env/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so
<VirtualHost *:80>
        ServerName kinujo-develop.c2sg.asia
        DocumentRoot /var/www

        Alias /static /var/www/kane_demo/static
        <Directory "/var/www/kane_demo/static">
                Options FollowSymLinks
                Order allow,deny
                Allow from all
                Require all granted
        </Directory>

        ErrorLog /var/log/httpd/kinujo_develop/error.log
        CustomLog /var/log/httpd/kinujo_develop/access.log combined

        WSGIPassAuthorization On
        WSGIDaemonProcess kane_demo python-home=/var/www/.env python-path=/var/www/kane_demo:/var/www/.env/lib/python3.7/site-packages
        WSGIProcessGroup kane_demo
        WSGIScriptAlias / /var/www/kinujo_develop/configs/wsgi_develop.py

        <Directory /var/www/kinujo_develop/configs>
      RewriteEngine on
      RewriteCond %{HTTP:X-Forwarded-Proto} !https [NC]
      RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]


                <Files wsgi_develop.py>
                        Order allow,deny
                        Allow from all
                        Require all granted
                </Files>
        </Directory>
</VirtualHost>
