# Generated by Django 3.0 on 2020-10-02 06:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand_name', models.CharField(default='', max_length=128)),
                ('pr', models.TextField()),
                ('url_str', models.CharField(max_length=255)),
                ('variety', models.SmallIntegerField(choices=[(0, 'NONE'), (1, 'HOROZONTAL'), (2, 'VERTICAL AND HOROZONTAL')], null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_opened', models.BooleanField(default=False)),
                ('opened_date', models.DateField(default=datetime.date.today)),
                ('target', models.SmallIntegerField(choices=[(0, 'ALL'), (1, 'GENERAL ONLY'), (2, 'STORE ONLY')], null=True)),
                ('price', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('store_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=11)),
                ('description', models.TextField()),
                ('is_draft', models.BooleanField(default=False)),
                ('is_food', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('vertical_and_horizontal', models.SmallIntegerField(choices=[(0, 'NONE'), (1, 'HOROZONTAL'), (2, 'VERTICAL AND HOROZONTAL')], null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVarietySelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(default='', max_length=255)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('product_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariety')),
            ],
        ),
        migrations.CreateModel(
            name='ProductJancode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan_code', models.CharField(default='', max_length=255)),
                ('stock', models.BigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('horizontal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jancode_horizontal', to='products.ProductVarietySelection')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jancode_vertical', to='products.ProductVarietySelection')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
    ]
