# Generated by Django 3.0 on 2020-10-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_payload'),
        ('products', '0002_auto_20201008_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='urser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
