# Generated by Django 3.0 on 2020-10-24 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productjancode',
            name='horizontal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jancode_horizontal', to='products.ProductVarietySelection'),
        ),
        migrations.AlterField(
            model_name='productjancode',
            name='vertical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jancode_vertical', to='products.ProductVarietySelection'),
        ),
        migrations.AlterField(
            model_name='productvarietyselection',
            name='product_variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariety'),
        ),
    ]
