# Generated by Django 3.0 on 2020-10-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201024_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_no',
            field=models.SmallIntegerField(null=True),
        ),
    ]
