# Generated by Django 3.0 on 2020-11-22 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201117_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariety',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productVarieties', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='productvarietyselection',
            name='product_variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productVarietySelections', to='products.ProductVariety'),
        ),
    ]
