# Generated by Django 3.0 on 2021-03-31 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210331_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_draft',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_food',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_opened',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_used',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='store_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_str',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
