# Generated by Django 3.0 on 2021-03-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210331_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productjancode',
            name='jan_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvariety',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvarietyselection',
            name='selection',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
