# Generated by Django 3.0 on 2021-10-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210331_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(default='', max_length=255),
        ),
    ]
