# Generated by Django 3.0 on 2021-10-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productcategory_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
