# Generated by Django 3.0 on 2021-12-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productcategory_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_sort_no',
            field=models.IntegerField(default=0),
        ),
    ]
