# Generated by Django 3.0 on 2021-12-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_featured_sort_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured_sort_no',
            new_name='recommended_sort_no',
        ),
    ]
